#!/bin/bash

set -e
# Clone so that we work on the staged version
rm -rf to-test
git clone . to-test
git diff --cached |patch -p1 -d to-test

# Test that it works with real ecosystem
set -x
cd to-test
sbcl --noinform --disable-ldb \
     --eval '(asdf:load-asd "to-test/tz-utilities.asd")' \
     --eval "(ql:quickload 'tz-utilities/test)" \
     --eval '(in-package tz-utilities-tests)' \
     --eval "(sb-ext:exit :abort
                (not (run-package-tests)))"