#!/bin/bash

set -e
# Clone so that we work on the staged version
rm -rf to-test
git clone . to-test
git diff --cached |patch -p1 -d to-test

# Test that it works with real ecosystem
set -x
cd to-test
sbcl --noinform --disable-ldb \
     --eval "(ql:quickload 'tz-utilities/test)" \
     --eval '(in-package tz-utilities-tests)' \
     --eval "(sb-ext:exit :abort (not (and (run-package-tests)(progn (ql:quickload 'tz-utilities/test/save-load)  (run-package-tests :package 'tz-utilities-tests-save-load)))))"
